apiVersion: v1
kind: Service
metadata:
  name: aleph
  labels:
    app: aleph
spec:
  ports:
    - name: http-aleph 
      port: 80
      protocol: TCP
      targetPort: 80
    - name: prometheus
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
      app: aleph