apiVersion: v1
kind: Service
metadata:
  name: beth
  labels:
    app: beth
spec:
  ports:
    - name: http-beth 
      port: 80
      protocol: TCP
      targetPort: 80
    - name: prometheus
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
      app: beth