apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
spec:
  ports:
    - name: http-front 
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
  selector:
      app: front