apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: {{ .Values.registry }}/front:{{ .Values.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80