---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aleph
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aleph
        version: v01
    spec:
      containers:
      - name: aleph
        image: localhost:32000/aleph:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aleph
  labels:
    app: aleph
spec:
  ports:
    - name: http-aleph 
      port: 80
      protocol: TCP
      targetPort: 80
    - name: prometheus
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
      app: aleph