---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aleph-v03
  namespace: games
spec:
  selector:
    matchLabels:
      app: aleph
  replicas: 2
  template:
    metadata:
      labels:
        app: aleph
        version: v03
    spec:
      containers:
      - name: aleph
        image: localhost:32000/aleph:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 80