---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aleph-v04
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: aleph
        version: v04
    spec:
      containers:
      - name: aleph
        image: localhost:32000/aleph:0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
