apiVersion: apps/v1
kind: Deployment
metadata:
  name: loader
spec:
  template:
    metadata:
      labels:
        app: loader
    spec:
      containers:
      - name: loader
        image: otomato/istio-games-loader:latest
        imagePullPolicy: Always
        command: 
        - sleep 
        - infinity
