apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: istio-prom
spec:
  rules:
  - host: prom.185.10.231.114.nip.io
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 9090
