apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front
  namespace: staging
spec:
  hosts:
  - "*"
  gateways:
  - alephbeth-gateway
  http:
  - route:
    - destination:
        host: front.staging.svc.cluster.local
        port:
          number: 80